<?php
declare(strict_types=1);

// Enable error reporting for debugging
error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('log_errors', '1');

// Initialize i18n system
require_once __DIR__.'/lib/i18n.php';
I18n::init();

// Skip all logic for healthcheck endpoint (Railway internal check)
$requestUri = $_SERVER['REQUEST_URI'] ?? '/';
if ($requestUri === '/health.php' || strpos($requestUri, '/health.php') === 0) {
    require __DIR__.'/health.php';
    exit;
}

// Handle static files (CSS, JS, images, etc.)
$path = parse_url($requestUri, PHP_URL_PATH) ?? '/';
if ($path !== '/' && file_exists(__DIR__ . $path) && !is_dir(__DIR__ . $path)) {
    // For production servers (Apache/Nginx), serve the file directly
    if (PHP_SAPI !== 'cli-server') {
        $filePath = __DIR__ . $path;
        $mimeType = mime_content_type($filePath);
        header('Content-Type: ' . $mimeType);
        header('Content-Length: ' . filesize($filePath));
        readfile($filePath);
        exit;
    }
    // For PHP's built-in server, let it handle the static file
    return false;
}

require __DIR__.'/config.php';
require __DIR__.'/bootstrap/canonical.php';
require __DIR__.'/bootstrap/config.php';
require __DIR__.'/lib/util.php';
require __DIR__.'/lib/seo.php';
require __DIR__.'/lib/links.php';

Canonical::guard();

// Send license link header for HTML pages
if (PHP_SAPI !== 'cli') {
  header('Link: <'.app_config('license_url').'>; rel="license"', false);
}

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';

// Redirect malformed URLs with /breadcrumb, /webpage, or /article appended
// These were incorrectly generated by the old nc_id() function that stripped # from fragment identifiers
// Examples: 
//   /services/schema-optimizer/rochester-ny/webpage -> /services/schema-optimizer/rochester-ny/
//   /insights/geo-16-framework/article -> /insights/geo-16-framework/
if (preg_match('#/(breadcrumb|webpage|article)(/|$)#', $path)) {
  // Remove all instances of /breadcrumb, /webpage, /article from the end of the path
  $cleanPath = preg_replace('#/(breadcrumb|webpage|article)+(/|$)#', '/', $path);
  $cleanPath = rtrim($cleanPath, '/') ?: '/';
  $canonicalUrl = Canonical::absolute($cleanPath);
  header('Location: '.$canonicalUrl, true, 301);
  exit;
}

// Redirect URLs with double language prefix (e.g., /ko/ko/page -> /ko/page)
// This can happen if language prefixes get doubled somehow
if (preg_match('#^/(ko|en)/(\1)(/|$)#', $path, $matches)) {
  // Remove the first duplicate language prefix (keep only one)
  $cleanPath = preg_replace('#^/(ko|en)/(\1)(/|$)#', '/$1$2', $path);
  $canonicalUrl = Canonical::absolute($cleanPath);
  header('Location: '.$canonicalUrl, true, 301);
  exit;
}

$path = Canonical::normalizePath($path);

// Handle language-specific routing
$currentLang = I18n::getCurrentLanguage();
$originalPath = $path; // Store original path for debugging
if ($currentLang !== I18n::getSupportedLanguages()[0]) { // Not default language
    // Remove language prefix from path for internal routing
    $path = preg_replace('/^\/' . preg_quote($currentLang, '/') . '(\/|$)/', '/', $path);
    if ($path === '') $path = '/';
}

$_GET = [];

$setPage = function (string $page, array $extra = []): void {
    $_GET['page'] = $page;
    foreach ($extra as $k => $v) {
        $_GET[$k] = $v;
    }
};

// Debug output for routing
if (isset($_GET['debug'])) {
    echo "Original Path: $originalPath\n";
    echo "Current Language: $currentLang\n";
    echo "Processed Path: $path\n";
    echo "Request URI: " . ($_SERVER['REQUEST_URI'] ?? 'N/A') . "\n";
}

switch (true) {
    case $path === '/':
        $setPage('home');
        break;
    case $path === '/about/':
        $setPage('about');
        break;
    case $path === '/services/':
        $setPage('services/index');
        break;
    case preg_match('#^/services/state/([a-z]{2})/$#', $path, $m):
        $_GET['state'] = $m[1];
        $setPage('services/state-hub');
        break;
    // Handle service + state name (e.g., /services/agentic-seo/texas)
    case preg_match('#^/services/([^/]+)/(texas|california|new-york|florida|illinois|washington|massachusetts|georgia|north-carolina|michigan|virginia|tennessee|arizona|colorado|oregon)(/|$)$#', $path, $m):
        $_GET['service'] = $m[1];
        // Convert state name to state key
        $stateMap = [
            'texas' => 'tx',
            'california' => 'ca',
            'new-york' => 'ny',
            'florida' => 'fl',
            'illinois' => 'il',
            'washington' => 'wa',
            'massachusetts' => 'ma',
            'georgia' => 'ga',
            'north-carolina' => 'nc',
            'michigan' => 'mi',
            'virginia' => 'va',
            'tennessee' => 'tn',
            'arizona' => 'az',
            'colorado' => 'co',
            'oregon' => 'or'
        ];
        $_GET['state'] = $stateMap[strtolower($m[2])] ?? strtolower($m[2]);
        $_GET['slug'] = $m[1];
        $setPage('service-state');
        break;
    case preg_match('#^/services/([^/]+)/([^/]+)/?$#', $path, $m):
        $_GET['service'] = $m[1];
        $_GET['city'] = $m[2];
        $setPage('services/city');
        break;
    case preg_match('#^/services/([^/]+)/$#', $path, $m):
        $_GET['service'] = $m[1];
        $setPage('services/service-hub');
        break;
    case preg_match('#^/city-service/([^/]+)/$#', $path, $m):
        $setPage('city-service', ['city' => $m[1]]);
        break;
    case $path === '/contact/':
        $setPage('contact');
        break;
    case $path === '/contact-confirmation/':
        $setPage('contact-confirmation');
        break;
    case $path === '/process-contact/':
        $setPage('process-contact');
        break;
    case $path === '/process-audit/':
        $setPage('process-audit');
        break;
    case $path === '/audit-results/':
        $setPage('audit-results');
        break;
    case $path === '/quote-thanks/':
        $setPage('quote-thanks');
        break;
    case $path === '/thanks/':
        $setPage('thanks');
        break;
    case $path === '/resources/':
    case $path === '/resources':
        $setPage('resources');
        break;
    case $path === '/resources/diagnostic/':
    case $path === '/resources/diagnostic':
        $setPage('resources/diagnostic');
        break;
    case $path === '/resources/llmo-optimization/':
    case $path === '/resources/llmo-optimization':
        $setPage('resources/llmo-optimization');
        break;
    case $path === '/insights/':
    case $path === '/insights':
        $setPage('insights/index');
        break;
    case $path === '/insights/geo-16-framework/':
    case $path === '/insights/geo-16-framework':
        $setPage('insights/geo-16-framework');
        break;
    case $path === '/insights/geo-16-framework/ko/':
    case $path === '/insights/geo-16-framework/ko':
        $setPage('insights/geo-16-framework/ko');
        break;
    case $path === '/resources/programmatic-seo-matrix-method/':
        require __DIR__.'/resources/programmatic-seo-matrix-method/index.php';
        exit;
    case $path === '/ai-consulting/':
        $setPage('ai-consulting/index');
        break;
    case preg_match('#^/ai-consulting/([^/]+)/$#', $path, $m):
        $setPage('ai-consulting/index');
        break;
    case $path === '/legal/license/':
        require __DIR__.'/pages/legal/license.php';
        exit;
    case preg_match('#^/industries/([^/]+)/$#', $path, $m):
        $setPage('industries/'.$m[1]);
        break;
    case preg_match('#^/case-studies/([^/]+)/$#', $path, $m):
        $setPage('case-studies/'.$m[1]);
        break;
    case $path === '/sitemap.xml':
        require __DIR__.'/public/sitemap.index.php';
        exit;
    case preg_match('#^/sitemaps/sitemap-(\d+)\.xml$#', $path, $m):
        $_GET['page'] = $m[1];
        require __DIR__.'/public/sitemap.page.php';
        exit;
    case $path === '/robots.txt':
        require __DIR__.'/public/robots.txt.php';
        exit;
    case $path === '/sitemap-city.xml.php':
        require __DIR__.'/sitemap-city.xml.php';
        exit;
    default:
        $trimmed = trim($path, '/');
        $setPage($trimmed !== '' ? $trimmed : 'home');
        break;
}

$page = $_GET['page'] ?? 'home';
$slug = $_GET['slug'] ?? null;
$city = $_GET['city'] ?? null;

$ctx = [
  'title' => 'Neural Command — Agentic SEO & AI Visibility',
  'desc'  => 'The only platform that turns your website into LLM‑ready training signals and agentic actions. If you have a product or service, we get it mentioned in ChatGPT and AI.',
];

if (strpos($page, '/') !== false) {
    $pagePath = $page;
    // Handle ai-consulting pages outside pages directory
    if (strpos($pagePath, 'ai-consulting/') === 0) {
        $pageFile = __DIR__.'/'.$pagePath.'.php';
    } else {
        $pageFile = __DIR__.'/pages/'.$pagePath.'.php';
    }
} else {
    $valid = ['home','about','services','service','service-city','service-state','state','city-service','process-audit','audit-results','contact','contact-confirmation','thanks','quote-thanks','services/service-hub','services/index','services/state-hub','services/city','process-contact','ai-consulting/index','resources','resources/diagnostic','resources/llmo-optimization','insights/index','insights/geo-16-framework','insights/geo-16-framework/ko'];
    if (!in_array($page,$valid)) {
        // Invalid page - return 404 instead of redirecting to homepage
        http_response_code(404);
        $page = '404';
        $pageFile = __DIR__.'/pages/404.php';
        if (!file_exists($pageFile)) {
            // If 404 page doesn't exist, create a simple one
            $pageFile = null;
        }
    } else {
        $pageFile = __DIR__.'/pages/'.$page.'.php';
    }
}

ob_start();
if ($pageFile && file_exists($pageFile)) {
    include $pageFile;
} else {
    // Page file doesn't exist - return 404, don't show homepage
    http_response_code(404);
    // Try to include a 404 page, otherwise show minimal error
    $errorPage = __DIR__.'/pages/404.php';
    if (file_exists($errorPage)) {
        include $errorPage;
    } else {
        // Minimal 404 response if no 404 page exists
        echo '<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>404 Not Found</h1><p>The requested page could not be found.</p></body></html>';
    }
}
$pageContent = ob_get_clean();

$breadcrumbsData = $GLOBALS['breadcrumbs'] ?? [];
unset($GLOBALS['breadcrumbs']);

$breadcrumbsHtml = '';
if (!empty($breadcrumbsData)) {
    $breadcrumbs = $breadcrumbsData;
    ob_start();
    include __DIR__.'/templates/breadcrumbs.php';
    $breadcrumbsHtml = ob_get_clean();
}

include __DIR__.'/templates/head.php';
include __DIR__.'/templates/header.php';

echo $breadcrumbsHtml;
echo $pageContent;

include __DIR__.'/templates/footer.php';

