<?php
// Process AI Visibility Diagnostic - Three-Layer Architecture
session_start();
require_once __DIR__.'/../config.php';
require_once __DIR__.'/../lib/util.php';
require_once __DIR__.'/../lib/diagnostic_analyzer.php';
require_once __DIR__.'/../lib/openai_diagnostic.php';

// Handle POST request
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: /resources/diagnostic/');
    exit;
}

$url = trim($_POST['url'] ?? '');
$email = trim($_POST['email'] ?? '');

// Validate input
if (!$url) {
    header('Location: /resources/diagnostic/?error=missing_url');
    exit;
}

// Layer 1: Deterministic Analysis
$signals = DiagnosticAnalyzer::analyze($url);

if (isset($signals['error'])) {
    $_SESSION['diagnostic_error'] = $signals['error'];
    header('Location: /resources/diagnostic/?error=analysis_failed&url=' . urlencode($url));
    exit;
}

// Layer 2: LLM Interpretation (if API key is configured)
$openai = new OpenAIDiagnostic();
$interpretation = $openai->interpret($signals);

// Store results in session
$_SESSION['diagnostic_results'] = [
    'url' => $url,
    'email' => $email,
    'signals' => $signals,
    'interpretation' => $interpretation,
    'timestamp' => gmdate('c')
];

// Send email notification if email provided
if ($email && filter_var($email, FILTER_VALIDATE_EMAIL)) {
    sendDiagnosticResults($url, $email, $signals, $interpretation);
}

// Redirect to results page
header('Location: /audit-results/');
exit;

/**
 * Send diagnostic results via email
 */
function sendDiagnosticResults($url, $email, $signals, $interpretation) {
    $to = $email;
    $subject = 'AI Visibility Diagnostic Results - ' . parse_url($url, PHP_URL_HOST);
    
    $body = "AI Visibility Diagnostic Results\n\n";
    $body .= "URL Analyzed: {$url}\n";
    $body .= "Analyzed: " . date('F j, Y \a\t g:i A') . "\n\n";
    
    $body .= "=== DETERMINISTIC SIGNALS ===\n\n";
    $body .= "Page Type: {$signals['page_type']}\n";
    $body .= "Page Role: {$signals['page_role_alignment']}\n";
    $body .= "Schema Types: " . implode(', ', $signals['schema_types'] ?: ['none']) . "\n";
    $body .= "Content Length: {$signals['content_structure']['content_length']} characters\n";
    $body .= "Has H1: " . ($signals['content_structure']['has_h1'] ? 'yes' : 'no') . "\n";
    $body .= "Internal Links: {$signals['internal_link_depth']['internal_links']}\n";
    $body .= "Canonical: " . ($signals['canonical_status']['present'] ? 'yes' : 'no') . "\n";
    $body .= "Noindex: " . ($signals['indexability']['noindex'] ? 'yes' : 'no') . "\n\n";
    
    if (!isset($interpretation['error']) && !isset($interpretation['fallback'])) {
        $body .= "=== AI INTERPRETATION ===\n\n";
        $body .= $interpretation['interpretation'] . "\n\n";
    }
    
    $body .= "---\n";
    $body .= "View full results: " . NC_BASEURL . "/audit-results/\n";
    $body .= "This diagnostic was generated by Neural Command.\n";
    
    $headers = [
        'From: ' . (NC_EMAIL_FROM ?: NC_CONTACT_EMAIL),
        'Reply-To: ' . NC_CONTACT_EMAIL,
        'X-Mailer: PHP/' . phpversion(),
        'Content-Type: text/plain; charset=UTF-8'
    ];
    
    mail($to, $subject, $body, implode("\r\n", $headers));
}
?>
